import energyArchetypes from "../assets/research/energy-archetypes.png";
import paperCover from "../assets/research/energy-paper-cover.png";
import airMap from "../assets/air-quality/pm25-prediction-map.png";
import airDashboard from "../assets/air-quality/pm25-dashboard.png";
import vrConcord from "../assets/vr/concord-pm25-particle-view.png";
import vrCity from "../assets/vr/city-scale-pollution-view.png";
import vrChart from "../assets/vr/high-low-pollution-chart.png";
import { Link } from "react-router-dom";
import { ComparisonMatrix, PublicationRecord, ResearchFigure, SectionHeader, SolarDiagram, SourceCaption, StatusLabel } from "../components";
import { externalPlatforms } from "../data/modules";
import { figures } from "../data/projectContent";

export default function ModulePage({type}){
  return ({energy:<EnergyPage/>,retrofit:<RetrofitPage/>,air:<AirPage/>,vr:<VRPage/>,renewable:<RenewablePage/>,scenario:<ScenarioPage/>})[type];
}
function ModuleHero({index,status,title,subtitle,children}){
  return <section className="module-editorial-hero"><div><span>{index} / MODULE</span><StatusLabel>{status}</StatusLabel></div><h1>{title}</h1><p>{subtitle}</p>{children}</section>
}
function NumberedRecords({items}){return <div className="numbered-records">{items.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div>}
function Figure({src,title,detail,source,status}){return <figure className="research-figure"><div className="figure-image"><img src={src} alt={title}/></div><SourceCaption title={title} detail={detail} source={source} status={status}/></figure>}

function EnergyPage(){
  return <div className="module-page editorial-page"><ModuleHero index="02" status="PUBLISHED RESEARCH · DATA AVAILABLE" title={<>Four housing types.<br/><em>5,832 simulated conditions.</em></>} subtitle="Physics-based energy simulation and machine-learning surrogate modeling for health-driven retrofit analysis."><Figure src={energyArchetypes} title="Four residential archetypes" detail="Single Family, Duplex, Quadplex, and Ten-Unit Apartment" source="Abbasabadi et al., Architecture 2026, 6, 84" status="Published research"/></ModuleHero>
    <section className="paper-section"><SectionHeader eyebrow="01 / Why these four archetypes" title="A defined residential study set." text="The archetypes establish the four housing forms used in the published modeling workflow."/><div className="archetype-editorial">{["Single Family","Duplex","Quadplex","Ten-Unit Apartment"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div></section>
    <section className="paper-section split-research"><div><span className="section-index">02 / ARCHETYPE GEOMETRY</span><h2>Geometry anchors the simulation record.</h2><p>Each archetype establishes a defined building form for parametric analysis.</p></div><ResearchFigure figure={figures.energyArchetypes}/></section>
    <section className="paper-section"><SectionHeader eyebrow="03 / Simulation Parameters" title="Conditions represented in the model"/><NumberedRecords items={[["Envelope","Insulation and window conditions."],["HVAC","System configurations represented in simulation."],["Ventilation","Outdoor-air and mechanical ventilation conditions."],["Hot water","Domestic hot-water system conditions."]]}/></section>
    <section className="paper-section method-band"><SectionHeader eyebrow="04 / EnergyPlus Workflow" title="Physics first. Surrogate model second." text="EnergyPlus simulations create the training record for machine-learning surrogate modeling."/><div className="method-line">{["Archetype definitions","Parametric conditions","EnergyPlus simulation","Model training","Recorded outputs"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div><p className="asset-note">The approved energy-method workflow image is not present in the supplied assets. No draft figure has been substituted.</p></section>
    <section className="paper-section"><SectionHeader eyebrow="05 / Model Outputs" title="Outputs remain attached to method and source." text="This interface does not reproduce unverified values or decorative result charts."/><div className="output-record"><span>MODEL OUTPUT CATEGORIES</span><p>Energy use · End-use demand · Simulation records · Surrogate-model estimates</p></div></section>
    <section className="paper-section"><SectionHeader eyebrow="06 / Publication Record" title="Published research"/><PublicationRecord image={paperCover}/></section></div>
}
function RetrofitPage(){
  const stages=[["Existing condition","Reference building condition","Baseline parameters","Reference for energy comparison","Reference for indoor environmental comparison"],["Envelope","Insulation, windows, and air sealing","Envelope properties","Changes heating and cooling loads","Changes infiltration pathways"],["Heat pump","Heating and cooling system","HVAC system type","Electrifies space conditioning","Changes thermal control"],["ERV / filtered ventilation","Mechanical ventilation and filtration","Airflow and filtration conditions","Adds fan and conditioning loads","Addresses ventilation and particle removal"],["Hot-water system","Domestic hot-water equipment","System type and efficiency","Changes water-heating demand","Supports whole-building comparison"],["Combined package","Multiple interventions together","Combined parameter set","Assessed as an integrated scenario","Assessed across energy and indoor conditions"]];
  return <div className="module-page editorial-page"><ModuleHero index="03" status="PUBLISHED RESEARCH · PROTOTYPE" title={<>Health-driven<br/><em>retrofit sequence.</em></>} subtitle="Interventions are recorded by what changes, the modeled parameter, and their energy and indoor-environment relevance."/><section className="paper-section"><ResearchFigure figure={figures.retrofit}/></section><section className="paper-section retrofit-sequence"><SectionHeader eyebrow="Intervention sequence" title="Existing condition to combined package"/>{stages.map((s,i)=><article key={s[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{s[0]}</h3><dl>{[["What changes",s[1]],["Modeled parameter",s[2]],["Energy relevance",s[3]],["Indoor environmental relevance",s[4]],["Data status","Published method / platform integration pending"]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></article>)}</section></div>
}
function AirPage(){
  return <div className="module-page editorial-page"><ModuleHero index="01" status="LIVE DATA CONNECTED · MODEL INTEGRATION IN PROGRESS" title={<>Making invisible<br/><em>exposure visible.</em></>} subtitle="Project visualizations connect current Clarity Air measurements with neighborhood PM2.5 model outputs across space and time."><Figure src={airMap} title="PM2.5 prediction visualization" detail="Neighborhood and grid-scale model output" source="DecarbCityTwin 2.0 project materials" status="Model integration in progress"/></ModuleHero><section className="paper-section"><SectionHeader eyebrow="01 / Data and prediction" title="Measurements and model outputs require distinct labels."/><div className="classification-row">{["MEASURED · Sensor observations","MODELED · Prediction output","ESTIMATED · Derived quantity","INTERPOLATED · Spatial estimate","HISTORICAL · Recorded period"].map(x=><span key={x}>{x}</span>)}</div></section><section className="paper-section figure-pair"><Figure src={airMap} title="PM2.5 prediction visualization" detail="Neighborhood and grid-scale model output" source="DecarbCityTwin 2.0 project materials" status="Modeled · Integration in progress"/><Figure src={airDashboard} title="PM2.5 time variation interface" detail="Dashboard view for examining temporal records" source="DecarbCityTwin 2.0 project materials" status="Project visualization"/></section><section className="paper-section"><NumberedRecords items={[["Spatial patterns","Maps display modeled variation across the study area."],["Live measurements","The Clarity Air server proxy supplies recent PM2.5, PM10, NO₂, temperature, and humidity records."],["Time variation","Dashboard records support comparison across time."],["VR translation","Particle number, size, motion, and density represent PM2.5 conditions in VR."]]}/><Link className="button air-live-entry" to="/analytics">Open Live Air Data ↗</Link></section></div>
}
function VRPage(){
  const vrBase=externalPlatforms.vr.replace(/\/+$/,"");
  const scenes=[
    {index:"01",label:"SCHOOL-SCALE PARTICLE MODEL",title:"Concord International School",description:"Explore the six-zone PM2.5 profile, hourly replay, changing sunlight, and local station readings.",image:vrConcord,href:`${vrBase}/#concord`},
    {index:"02",label:"NEIGHBORHOOD-SCALE DIGITAL TWIN",title:"South Park, Seattle",description:"Explore road-network PM2.5 movement using observed weather conditions and the restored GIS model.",image:vrCity,href:`${vrBase}/#south-park`}
  ];
  return <div className="vr-page">
    <ModuleHero index="06" status="WORKING WEBXR PROTOTYPE" title={<>Step inside the<br/><em>city&apos;s atmosphere.</em></>} subtitle="Choose a scene below to move from the DecarbCityTwin research platform into its interactive 3D and headset-ready WebXR environment."/>
    <section className="vr-entry-section">
      <header className="vr-entry-heading"><div><span>01 / IMMERSIVE SCENES</span><h2>Choose an environment.</h2></div><p>Each scene opens the working 3D application directly. Explore on desktop with a mouse and keyboard, or select Enter VR inside the scene with a compatible browser and headset.</p></header>
      <div className="vr-scene-grid">
        {scenes.map(scene=><a className="vr-scene-card" href={scene.href} target="_blank" rel="noreferrer" key={scene.index}>
          <span className="vr-scene-index">{scene.index}</span>
          <div className="vr-scene-image"><img src={scene.image} alt={`${scene.title} interactive VR scene preview`}/><span>OPEN INTERACTIVE SCENE ↗</span></div>
          <div className="vr-scene-copy"><small>{scene.label}</small><h3>{scene.title}</h3><p>{scene.description}</p></div>
        </a>)}
      </div>
    </section>
    <section className="vr-editorial"><div className="vr-intro"><span>02 / EXPERIENCE MODEL</span><h2>Time is visible.<br/>Exposure conditions change.</h2><p>The moving sun marks the passage of time through a 24-hour cycle. PM2.5 is represented through changes in particle number, size, motion, and density.</p></div><Figure src={vrChart} title="Highest- and lowest-pollution conditions" detail="Comparison across the represented 00:00–23:00 cycle" source="DecarbCityTwin 2.0 VR project materials" status="Working prototype"/></section>
    <section className="vr-cta"><span>COMMUNITY ENGAGEMENT / IMMERSIVE MODE</span><h2>Two scales. One environmental story.</h2><p>Begin at Concord International School or move across the South Park neighborhood.</p><a className="button light-button" href={`${vrBase}/#concord`} target="_blank" rel="noreferrer">Enter Concord VR ↗</a></section>
  </div>
}
function RenewablePage(){
  return <div className="module-page editorial-page"><ModuleHero index="04" status="IN DEVELOPMENT" title={<>Geometry, demand,<br/><em>and renewable records.</em></>} subtitle="This module is being developed to connect building geometry, renewable-energy potential, and building energy demand within the South Park digital twin."><SolarDiagram/></ModuleHero><section className="paper-section"><NumberedRecords items={[["Research question","How can building geometry and energy demand be connected to renewable-energy scenario records?"],["Available building geometry","The digital twin provides the spatial structure for future approved analysis."],["Rooftop and façade opportunity","Candidate surfaces will be represented without unpublished material or numerical claims."],["Connection to energy demand","Future records will link generation estimates to modeled building demand."],["Scenario records","Baseline, PV, and combined scenarios will retain source and status metadata."],["Future approved outputs","Public figures will be added only after approval."]]}/></section></div>
}
function ScenarioPage(){
  return <div className="module-page editorial-page"><ModuleHero index="05" status="PLANNED PLATFORM LAYER" title="Agentic AI" subtitle="Guided querying, scenario comparison, and grounded explanation using project data, scenario records, and the knowledge graph."><ComparisonMatrix/></ModuleHero><section className="paper-section"><SectionHeader eyebrow="Comparison structure" title="Records before recommendations." text="Each scenario requires a source, method, status, assumptions, and uncertainty record."/><div className="scenario-record-table"><div>Scenario</div><div>Source</div><div>Status</div><div>Evidence record</div>{["Baseline","Envelope","Electrification","PV","Combined"].map(x=><div className="scenario-record-row" key={x}><strong>{x}</strong><span>Pending</span><span>Planned</span><span>Not yet connected</span></div>)}</div></section></div>
}
