import paperCover from "../assets/research/energy-paper-cover.png";
import frameworkReference from "../assets/framework/integrated-platform-framework.png";
import { PublicationRecord, ResearchFigure, SectionHeader, SourceCaption } from "../components";
import { figures, frameworkStages } from "../data/projectContent";

export default function Research(){
  return <div className="research-page editorial-page">
    <section className="research-intro"><div className="page-container"><h1>Research</h1><p>DecarbCityTwin brings together environmental sensing, building-energy simulation, retrofit analysis, renewable-energy scenarios, knowledge-graph reasoning, agentic decision support, and immersive interfaces. This page documents the study context, methods, platform framework, and research outputs supporting the South Park testbed.</p></div></section>
    <section className="paper-section"><div className="page-container"><SectionHeader eyebrow="01 / Project Context" title="Why South Park" text="South Park is studied at the intersection of environmental exposure, building performance, energy burden, health, renewable-energy opportunity, and neighborhood resilience."/><div className="context-list"><article><b>01</b><h3>Air pollution and exposure</h3></article><article><b>02</b><h3>Building energy performance</h3></article><article><b>03</b><h3>Renewable-energy opportunity</h3></article></div></div></section>
    <section className="paper-section"><div className="page-container"><SectionHeader eyebrow="02 / Research Workflow" title="Simulation and Data-Driven Modeling" text="The existing research workflow connects city and building data, localized prototype models, physics-based EnergyPlus simulations, synthetic datasets, machine-learning model development, evaluation, and retrofit-strategy analysis."/><figure className="research-figure"><div className="figure-image"><img src={figures.energyWorkflow.src} alt="Energy modeling and surrogate-model workflow"/></div><SourceCaption title="Energy modeling and surrogate-model workflow" detail="From localized building models and physics-based simulations to model evaluation and retrofit-strategy analysis." source="DecarbCityTwin project materials" status="Existing research workflow"/></figure></div></section>
    <IntegratedFramework reference={frameworkReference}/>
    <section className="paper-section methods-section"><div className="page-container"><SectionHeader eyebrow="04 / Building Archetypes" title="Residential Archetypes for Energy Simulation" text="Four representative residential archetypes provide the building-model foundation for parametric simulation and health-driven retrofit analysis."/><ResearchFigure figure={figures.energyArchetypes}/></div></section>
    <section className="paper-section outputs-section"><div className="page-container"><SectionHeader eyebrow="05 / Research Outputs" title="Published research"/><PublicationRecord image={paperCover}/></div></section>
    <section className="paper-section team-section" id="team"><div className="page-container"><SectionHeader eyebrow="06 / Team and Partners" title="Research team and collaborators" text="Names and partner marks will be added when approved."/><div className="team-record"><div><span>LAB</span><strong>Sustainable Intelligence Lab</strong></div><div><span>INSTITUTION</span><strong>University of Washington</strong></div><div><span>COMMUNITY + PROJECT PARTNERS</span><strong>Approved records pending</strong></div></div></div></section>
  </div>
}

function IntegratedFramework({reference}){
  return <section className="paper-section framework-section"><div className="page-container"><SectionHeader eyebrow="03 / Platform Framework" title="Integrated Platform Framework" text="Five connected stages organize sources, infrastructure, semantic relationships, decision support, and interfaces."/><div className="framework-flow">{frameworkStages.map(([title,items],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul>{i<4&&<b aria-hidden="true">→</b>}</article>)}</div><blockquote>The web platform is the primary digital twin interface, while VR operates as an immersive mode connected to the same data, models, scenarios, knowledge graph, cloud services, and agentic reasoning layer.</blockquote><details><summary>Reference architecture diagram</summary><img src={reference} alt="Integrated platform framework structural reference"/></details></div></section>
}
